"""empty message

Revision ID: 2aabc7990a7f
Revises: 273b5943b33e
Create Date: 2016-08-02 18:18:45.916156

"""

# revision identifiers, used by Alembic.
revision = '2aabc7990a7f'
down_revision = '273b5943b33e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_column('playlist', 'hash_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('hash_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    ### end Alembic commands ###
