"""empty message

Revision ID: b6755c21184f
Revises: 2aabc7990a7f
Create Date: 2016-08-02 18:43:13.950638

"""

# revision identifiers, used by Alembic.
revision = 'b6755c21184f'
down_revision = '2aabc7990a7f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_json', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('playlist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('json_state', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'playlist_pkey')
    )
    op.drop_table('collection')
    ### end Alembic commands ###
